build(CI): - fix jacoco test report fail v3

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -72,9 +72,12 @@ jobs:
             ./gradlew jacocoReport --rerun-tasks --no-build-cache
             echo "**************** "
             echo "**************** "
+            echo "Checking if Jacoco report exists..."
+            ls app/build/reports/jacoco/jacocoTestReport
+            cat app/build/reports/jacoco/jacocoTestReport/jacocoTestReport.xml || echo " XXXXXXXXXXXXXX Jacoco report not found"
             echo "**************** "
             echo "@@@@@@@@@@@@@@@@   [SonarCloud Analysis...]"
-            ./gradlew sonarqube \
+            ./gradlew sonar\
               -Dsonar.projectKey=JumpingKeyCaps_OCR_Projet16_Exercice \
               -Dsonar.organization=jumpingkeycaps \
               -Dsonar.host.url=https://sonarcloud.io \
